### ISSUE TITLE
Question About Using this Plugin

### ISSUE THREAD

**Issue by YantianZha** [robcog-iai/UROSWorldControl#19]
Hello,

I am trying to use RL to control a robot in an Unreal Engine environment, and I found this repo could be helpful. Do you know if I can use this plugin together with a ROS server to load a robot into UE Editor, and then convert the environment into a binary with an already-loaded robot? Then my RL agent (e.g. by using [gym-unrealcv](https://github.com/zfw1226/gym-unrealcv)) could send some commands to control the robot in the binary.

Another possible way is the binary would not include the robot, but the robot could be imported by a gym-ros sever into the binary in a real-time fashion.

Also it would be great if you can provide an example of ROS-UE server (might be a ros script + a uproject file), and a ROS client file.

Thank you!

**Comment by andreihaidu** [comment]
Hi, for now the plugins are mostly tailored for our internal use. I did not test creating a binary of the environment, it might require some extra preprocessor flags.
